# theme = "MyCustom"
theme = "autumn_night"
# theme = "ayu_evolve"

[editor]
line-number = "relative"
color-modes = true
end-of-line-diagnostics = "hint"
clipboard-provider = "wayland"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
# character = "|" 
# skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"
